### ISSUE TITLE
Broken in Gradle in combination with test resources

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-control-panel#55]
### Expected Behavior

Should work

### Actual Behaviour

Fails with:

```
java.lang.IllegalStateException: No JsonMapper implementation found
        at io.micronaut.json.JsonMapper.lambda$createDefault$2(JsonMapper.java:367)
        at java.base/java.util.Optional.orElseThrow(Optional.java:403)
        at io.micronaut.json.JsonMapper.createDefault(JsonMapper.java:367)
 
```

### Steps To Reproduce

Create a project with test resources and control panel

### Version

4.1.3

**Comment by ZacharyKlein** [comment]
FWIW, a workaround is to add the `io.micronaut:micronaut-jackson-databind` dependency (in place or or in addition to `micronaut-serde`).

**Comment by ZacharyKlein** [comment]
(This is still an issue as of 4.2.1)

**Comment by melix** [comment]
Right I reproduced with `mn create-app --build=gradle_kotlin --jdk=17 --lang=java --test=junit --features=control-panel,data-jdbc,postgres com.example.cptestr` and running `./gradlew run`.

However, the test resources client intentionally doesn't depend on any explicit json mapper, so I am wondering if the issue is not in `control-panel` instead. The only thing I'm doing in test resources is getting the default mapper: https://github.com/micronaut-projects/micronaut-test-resources/blob/909f3c578164b4bc12c46120f880047ee4ce1ae7/test-resources-client/src/main/java/io/micronaut/testresources/client/DefaultTestResourcesClient.java#L73

@alvarosanchez wdyt?

**Comment by alvarosanchez** [comment]
The question is why this reproduces with Control Panel during startup

**Comment by melix** [comment]
So starter adds `developmentOnly` dependencies, but I see nothing suspicious. Both the test resources client and control panel depend on `json-core`, but no explicit mapper :thinking: https://scans.gradle.com/s/fcoofeyyk3s5s/dependencies?dependencies=json&expandAll&focusedDependency=WzAsMCw4NSxbMCwwLFsxXV1d&focusedDependencyView=versions

**Comment by alvarosanchez** [comment]
Root cause is:

```
io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [io.micronaut.controlpanel.core.config.ControlPanelModuleConfiguration] exists. 
```

Which is hidden by the Object Mapper context initialisation.
